"""Who generates the round trips: the agent, or the regime label underneath it.

The gate caps rotation at 30% of decisions and the best run so far sits at 32% counting
direction changes only, which is a marginal but real failure. Before changing anything it
is worth knowing whose decision each round trip was.

The regime label flips on 37% of transitions in that run and 31% of transitions invert the
default exposure, because regime 0 defaults to cash and regime 3 defaults to invested and
the sequence alternates between them. So the suspicion is that the churn is generated by an
unstable classifier rather than by the agent changing its mind, and that the burden of
proof is anchored to a label that moves faster than the strategies it selects intend to
hold: regime 3 declares a 168 hour horizon while the label flips every 5 day step.

This prints every opening and every full exit with what the agent asked for and whether the
playbook overrode it, which settles the question either way.

Usage:
    python -m research.churn_source [report.json]
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

from btc_decision_agent.application.llm_tools import EXPOSURE_INVESTED
from btc_decision_agent.application.regime_playbook import strategy_for

DUST = 0.01


def main() -> int:
    path = Path(sys.argv[1] if len(sys.argv) > 1 else "data/validation/llm-agent-backtest.json")
    if not path.is_file():
        print(f"informe no encontrado: {path}")
        return 2
    payload = json.loads(path.read_text(encoding="utf-8"))
    trace: list[dict[str, Any]] = payload.get("trace") or []
    if not trace:
        print("traza vacia")
        return 1

    print("=" * 94)
    print(f"DE DONDE SALE LA ROTACION  ·  {path.name}")
    print(
        f"  agente {payload['llm_agent']['net_return_pct']:+.2f}%, "
        f"{len(trace)} decisiones, {payload['llm_agent']['stop_exits']} salidas por stop"
    )
    print("=" * 94)

    flips = inverting = 0
    for index in range(1, len(trace)):
        previous, current = trace[index - 1].get("regime"), trace[index].get("regime")
        if previous == current:
            continue
        flips += 1
        before = strategy_for(previous).default_exposure == EXPOSURE_INVESTED
        after = strategy_for(current).default_exposure == EXPOSURE_INVESTED
        if before != after:
            inverting += 1
    transitions = max(1, len(trace) - 1)
    print(
        f"  la etiqueta de regimen cambia en {flips}/{transitions} transiciones "
        f"= {flips / transitions:.0%}"
    )
    print(
        f"  de esas, {inverting} INVIERTEN la exposicion por defecto "
        f"= {inverting / transitions:.0%} de las transiciones"
    )
    print()
    print("  " + "".join(str(item.get("regime", "?")) for item in trace))
    print()

    print(f"  {'regimen':>8} {'dec':>4} {'impuestas':>10}  lo que pidio el agente")
    print("  " + "-" * 66)
    for regime in sorted({int(item["regime"]) for item in trace if item.get("regime") is not None}):
        rows = [item for item in trace if item.get("regime") == regime]
        forced = [item for item in rows if not item.get("choice_honoured", True)]
        asked = Counter(item.get("agent_asked_for") for item in rows)
        print(
            f"  {regime:>8} {len(rows):>4} {len(forced):>10}  "
            f"{dict(asked)}  (por defecto: {strategy_for(regime).default_exposure})"
        )

    for title, predicate in (
        (
            "CIERRES TOTALES",
            lambda item: item["adjustment"] == "VENDER" and float(item["share_target"]) <= DUST,
        ),
        (
            "APERTURAS",
            lambda item: item["adjustment"] == "COMPRAR" and float(item["share_before"]) <= DUST,
        ),
    ):
        print()
        chosen = [item for item in trace if predicate(item)]
        print(f"  {title}: {len(chosen)}")
        for item in chosen:
            honoured = item.get("choice_honoured")
            mark = "" if honoured else "   <- IMPUESTO POR EL PLAYBOOK"
            print(
                f"    dia {item['day_index']} r{item['regime']} "
                f"el agente pidio {item['agent_asked_for']:<11} "
                f"conv {item['conviction']:.2f}{mark}"
            )
    return 0


if __name__ == "__main__":
    sys.exit(main())
