"""Tests for the regime taxonomy, with the look-ahead firewall as the centrepiece.

The firewall test exists because the oracle labeller is acausal on purpose. In a codebase
where eight structural defects all had the same shape -- an intention declared and nothing
checking it -- an "only for scoring" comment is not a control. These tests are the control.
"""

from __future__ import annotations

import inspect
import math
from datetime import UTC, datetime, timedelta

from regime_taxonomy import (
    DailyBar,
    RegimeFeatures,
    RegimeParams,
    apply_min_dwell,
    apply_persistence,
    causal_features,
    classify,
    detect_regimes,
    drawdown_from_peak,
    efficiency_ratio,
    enforce_min_segment,
    oracle_regimes,
    percentile_rank,
    realised_volatility,
    regime_shares,
    score_detection,
    transitions,
)


def _daily(closes: list[float], *, start_run: int = 1) -> list[DailyBar]:
    """A contiguous run of synthetic daily bars with the given closes.

    Dates are generated by offsetting a base day, because the drawdown axis needs a
    180-day peak window and these series therefore run much longer than a month.
    """
    base = datetime(2022, 1, 1, tzinfo=UTC)
    bars: list[DailyBar] = []
    for index, close in enumerate(closes):
        bars.append(
            DailyBar(
                date=(base + timedelta(days=index)).strftime("%Y-%m-%d"),
                open_time_ms=index * 86_400_000,
                open=close,
                high=close * 1.01,
                low=close * 0.99,
                close=close,
                hours=24,
                contiguous_run=start_run + index,
            )
        )
    return bars


class TestLookAheadFirewall:
    """The causal path must not be able to reach the oracle, by signature or by call."""

    def test_the_causal_detector_does_not_accept_oracle_labels(self) -> None:
        parameters = set(inspect.signature(detect_regimes).parameters)
        assert parameters == {"daily", "params"}, (
            "detect_regimes gained an argument; if it is an oracle or a future-looking "
            "series, the study's central claim is void"
        )

    def test_no_function_on_the_causal_path_calls_the_oracle(self) -> None:
        for function in (detect_regimes, causal_features, classify, apply_persistence):
            source = inspect.getsource(function)
            assert "oracle" not in source.lower(), (
                f"{function.__name__} mentions the oracle; the causal path must not see it"
            )

    def test_causal_features_at_day_t_ignore_everything_after_t(self) -> None:
        rising = [100.0 * (1.01**index) for index in range(300)]
        truncated = causal_features(_daily(rising[:250]), RegimeParams())
        full = causal_features(_daily(rising), RegimeParams())
        for index in range(250):
            assert truncated[index] == full[index], (
                f"day {index} changed when later data was appended: look-ahead"
            )

    def test_the_oracle_by_contrast_does_change_with_future_data(self) -> None:
        """Confirms the oracle really is acausal, so the comparison above means something."""
        path = [100.0 * (1.01**index) for index in range(300)]
        short = oracle_regimes(_daily(path[:250]))
        long = oracle_regimes(_daily(path))
        assert short[:250] != long[:250]


class TestEfficiencyRatio:
    def test_a_straight_line_is_perfectly_efficient(self) -> None:
        assert efficiency_ratio([1.0, 2.0, 3.0, 4.0]) == 1.0

    def test_a_round_trip_is_perfectly_inefficient(self) -> None:
        assert efficiency_ratio([1.0, 2.0, 1.0]) == 0.0

    def test_a_flat_path_is_undefined_not_zero(self) -> None:
        assert efficiency_ratio([5.0, 5.0, 5.0]) is None

    def test_direction_does_not_change_efficiency(self) -> None:
        assert efficiency_ratio([4.0, 3.0, 2.0, 1.0]) == 1.0


class TestVolatilityAndRank:
    def test_constant_returns_have_no_dispersion(self) -> None:
        geometric = [100.0 * (1.01**index) for index in range(10)]
        volatility = realised_volatility(geometric)
        assert volatility is not None
        assert volatility < 1e-12

    def test_rank_is_the_fraction_at_or_below(self) -> None:
        assert percentile_rank(3.0, [1.0, 2.0, 3.0, 4.0]) == 0.75

    def test_rank_without_reference_is_withheld(self) -> None:
        assert percentile_rank(3.0, []) is None


class TestClassification:
    def test_a_sustained_rise_is_labelled_bullish(self) -> None:
        labels = detect_regimes(_daily([100.0 * (1.012**index) for index in range(260)]))
        assert labels[-1] == "ALCISTA"

    def test_a_sustained_fall_is_labelled_bearish(self) -> None:
        labels = detect_regimes(_daily([100.0 * (0.988**index) for index in range(260)]))
        assert labels[-1] == "BAJISTA"

    def test_a_calm_market_pinned_at_its_peak_is_bullish_not_sideways(self) -> None:
        """Documents what the drawdown axis actually claims, which is not obvious.

        ALCISTA means "above trend and within 10% of the running peak". A market going
        nowhere AT its highs satisfies that, so it is bullish by this definition, not
        sideways. LATERAL is therefore NOT "a flat market": it is the calm bucket that sits
        in a mild pullback BELOW the peak. Naming it wrongly in a report would misdescribe
        the only regime that meets the success criterion.
        """
        path = [100.0 + 0.5 * math.sin(index / 2.0) for index in range(260)]
        assert detect_regimes(_daily(path))[-1] == "ALCISTA"

    def test_lateral_is_the_calm_bucket_below_the_peak(self) -> None:
        features = RegimeFeatures(
            date="2023-03-01",
            close=100.0,
            efficiency=0.1,
            window_return=0.0,
            volatility=0.01,
            volatility_rank=0.20,
            drawdown=0.15,
            price_over_ma=-0.02,
        )
        assert classify(features, RegimeParams(direction_axis="drawdown")) == "LATERAL"

    def test_warmup_is_unlabelled_rather_than_guessed(self) -> None:
        labels = detect_regimes(_daily([100.0 * (1.01**index) for index in range(40)]))
        assert labels[0] is None

    def test_a_lookback_spanning_many_absent_days_withholds_the_label(self) -> None:
        """Coverage, not an unbroken streak, is what decides. A real hole still abstains."""
        bars = _daily([100.0 * (1.01**index) for index in range(260)])
        # Drop 40 consecutive calendar days from the middle: the 180-day lookback now
        # stretches across far more calendar time than it has bars for.
        holed = [*bars[:120], *bars[160:]]
        features = causal_features(holed, RegimeParams())
        assert classify(features[185], RegimeParams()) is None

    def test_a_single_missing_day_does_not_erase_the_history(self) -> None:
        """The defect this guards: one absent day used to withhold the next six months.

        An unbroken-streak rule deleted 723 days -- all of 2020 and 2021 -- because the
        dataset has a handful of 1-5 hour gaps. The conclusion drawn from that ("LATERAL
        never occurs in 2020-2022") was a statement about the instrument, not the market.
        """
        bars = _daily([100.0 * (1.01**index) for index in range(300)])
        holed = [*bars[:100], *bars[101:]]  # exactly one calendar day missing
        features = causal_features(holed, RegimeParams())
        assert classify(features[250], RegimeParams()) is not None


class TestPersistence:
    def test_a_single_dissenting_day_cannot_flip_the_label(self) -> None:
        standing: list[str | None] = ["ALCISTA"] * 10 + ["BAJISTA"] + ["ALCISTA"] * 10
        settled = apply_persistence(standing, 5)  # type: ignore[arg-type]
        assert set(settled) == {"ALCISTA"}

    def test_a_sustained_challenger_does_flip_it(self) -> None:
        standing: list[str | None] = ["ALCISTA"] * 10 + ["BAJISTA"] * 10
        settled = apply_persistence(standing, 5)  # type: ignore[arg-type]
        assert settled[-1] == "BAJISTA"

    def test_persistence_costs_exactly_the_days_it_demands(self) -> None:
        """Five means five: adoption lands on the fifth consecutive challenger day."""
        standing: list[str | None] = ["ALCISTA"] * 10 + ["BAJISTA"] * 10
        settled = apply_persistence(standing, 5)  # type: ignore[arg-type]
        assert settled[14] == "BAJISTA"
        assert settled[13] == "ALCISTA"

    def test_disabling_persistence_passes_labels_through(self) -> None:
        standing: list[str | None] = ["ALCISTA", "BAJISTA", "ALCISTA"]
        assert apply_persistence(standing, 1) == standing  # type: ignore[arg-type]


class TestDetectionScoring:
    def test_a_perfect_detector_has_no_lag_and_no_false_alarms(self) -> None:
        labels: list[str | None] = ["ALCISTA"] * 20 + ["BAJISTA"] * 20
        quality = score_detection(labels, labels)  # type: ignore[arg-type]
        assert quality.median_lag_days == 0.0
        assert quality.false_alarms == 0
        assert quality.coverage == 1.0

    def test_a_late_detector_reports_its_lag(self) -> None:
        oracle: list[str | None] = ["ALCISTA"] * 20 + ["BAJISTA"] * 20
        late: list[str | None] = ["ALCISTA"] * 27 + ["BAJISTA"] * 13
        quality = score_detection(late, oracle)  # type: ignore[arg-type]
        assert quality.median_lag_days == 7.0

    def test_switching_to_the_wrong_regime_is_not_scored_as_a_detection(self) -> None:
        oracle: list[str | None] = ["ALCISTA"] * 20 + ["BAJISTA"] * 20
        wrong: list[str | None] = ["ALCISTA"] * 20 + ["LATERAL"] * 20
        quality = score_detection(wrong, oracle)  # type: ignore[arg-type]
        assert quality.matched == 0
        assert quality.missed == 1
        assert quality.false_alarms == 1

    def test_transitions_ignore_the_first_label_and_the_nones(self) -> None:
        labels: list[str | None] = [None, None, "LATERAL", "LATERAL", "ALCISTA"]
        assert transitions(labels) == [(4, "ALCISTA")]  # type: ignore[arg-type]


class TestShares:
    def test_shares_sum_to_one_and_ignore_unlabelled_days(self) -> None:
        labels: list[str | None] = [None, "ALCISTA", "ALCISTA", "LATERAL", "BAJISTA"]
        shares = regime_shares(labels)  # type: ignore[arg-type]
        assert abs(sum(shares.values()) - 1.0) < 1e-12
        assert shares["ALCISTA"] == 0.5

class TestMinimumDwellIsCausal:
    """The near-miss that produced this class: minimum duration must not read the future.

    `enforce_min_segment` decides whether a run was long enough by inspecting the whole
    series, which on day t means knowing how long the current run will END UP being. That
    is look-ahead. `apply_min_dwell` asks instead how long the standing label has ALREADY
    held, which only the past can answer. The first belongs to the oracle, the second to
    the detector, and swapping them silently flatters a backtest.
    """

    def test_dwell_at_day_t_is_unchanged_by_appending_future_days(self) -> None:
        labels: list[str | None] = ["ALCISTA"] * 40 + ["BAJISTA"] * 40
        short = apply_min_dwell(labels[:50], 30)  # type: ignore[arg-type]
        long = apply_min_dwell(labels, 30)  # type: ignore[arg-type]
        assert short == long[:50]

    def test_enforce_min_segment_by_contrast_does_read_the_future(self) -> None:
        labels: list[str | None] = ["ALCISTA"] * 40 + ["BAJISTA"] * 40
        short = enforce_min_segment(labels[:50], 30)  # type: ignore[arg-type]
        long = enforce_min_segment(labels, 30)  # type: ignore[arg-type]
        assert short != long[:50]

    def test_an_adopted_label_is_held_for_the_full_dwell_and_this_costs_lag(self) -> None:
        """The dwell does not suppress a blip, it LOCKS IT IN for min_days.

        That is the honest cost of the churn control and it is stated rather than hidden:
        a four-day challenger that gets through becomes a 30-day regime, which adds lag.
        `apply_persistence` is what filters blips; the dwell is what forbids short runs.
        """
        labels: list[str | None] = ["LATERAL"] * 40 + ["BAJISTA"] * 4 + ["LATERAL"] * 40
        settled = apply_min_dwell(labels, 30)  # type: ignore[arg-type]
        assert settled.count("BAJISTA") == 30

    def test_persistence_is_what_actually_filters_a_blip(self) -> None:
        """A challenger shorter than `persistence_days` never becomes the standing label."""
        labels: list[str | None] = ["LATERAL"] * 40 + ["BAJISTA"] * 4 + ["LATERAL"] * 40
        assert "BAJISTA" not in apply_persistence(labels, 5)  # type: ignore[arg-type]

    def test_a_challenger_that_reaches_the_threshold_is_adopted(self) -> None:
        labels: list[str | None] = ["LATERAL"] * 40 + ["BAJISTA"] * 5 + ["LATERAL"] * 40
        assert "BAJISTA" in apply_persistence(labels, 5)  # type: ignore[arg-type]

    def test_a_long_lived_challenger_does_replace_the_standing_label(self) -> None:
        labels: list[str | None] = ["LATERAL"] * 40 + ["BAJISTA"] * 40
        assert apply_min_dwell(labels, 30)[-1] == "BAJISTA"  # type: ignore[arg-type]

    def test_the_detector_never_emits_a_run_shorter_than_the_dwell(self) -> None:
        """The property the artifact violated: no 4-day 'regimes'."""
        path = [100.0 * (1.0 + 0.02 * math.sin(index / 9.0)) for index in range(500)]
        labels = detect_regimes(_daily(path), RegimeParams(min_regime_days=30))
        runs: list[int] = []
        current = 1
        for index in range(1, len(labels)):
            if labels[index] == labels[index - 1]:
                current += 1
            else:
                runs.append(current)
                current = 1
        interior = runs[1:]  # The first run includes the unlabelled warmup.
        assert all(length >= 30 for length in interior), interior


class TestDrawdownAxis:
    def test_a_window_ending_at_its_peak_has_no_drawdown(self) -> None:
        assert drawdown_from_peak([1.0, 2.0, 3.0]) == 0.0

    def test_drawdown_is_measured_from_the_highest_close(self) -> None:
        assert drawdown_from_peak([100.0, 200.0, 150.0]) == 0.25

    def test_the_bear_is_tested_before_the_residual_buckets(self) -> None:
        """Defect from iteration 1: the losing regime must not hide in a leftover bucket."""
        features = RegimeFeatures(
            date="2022-06-01",
            close=20000.0,
            efficiency=0.1,
            window_return=-0.5,
            volatility=0.05,
            volatility_rank=0.95,
            drawdown=0.55,
            price_over_ma=-0.30,
        )
        assert classify(features, RegimeParams(direction_axis="drawdown")) == "BAJISTA"
